public abstract class io.netty.util.concurrent.AbstractFuture extends java.lang.Object implements io.netty.util.concurrent.Future
{
public void <init>()
{
io.netty.util.concurrent.AbstractFuture v0;
v0 := @this: io.netty.util.concurrent.AbstractFuture;
specialinvoke v0.<java.lang.Object: void <init>()>();
return;
}
public java.lang.Object get() throws java.lang.InterruptedException, java.util.concurrent.ExecutionException
{
java.lang.Throwable v1;
java.util.concurrent.ExecutionException v4;
io.netty.util.concurrent.AbstractFuture v0;
java.lang.Object v2;
boolean v3;
v0 := @this: io.netty.util.concurrent.AbstractFuture;
virtualinvoke v0.<io.netty.util.concurrent.AbstractFuture: io.netty.util.concurrent.Future await()>();
v1 = virtualinvoke v0.<io.netty.util.concurrent.AbstractFuture: java.lang.Throwable cause()>();
if v1 != null goto label1;
v2 = virtualinvoke v0.<io.netty.util.concurrent.AbstractFuture: java.lang.Object getNow()>();
return v2;
label1:
v3 = v1 instanceof java.util.concurrent.CancellationException;
if v3 == 0 goto label2;
throw v1;
label2:
v4 = new java.util.concurrent.ExecutionException;
specialinvoke v4.<java.util.concurrent.ExecutionException: void <init>(java.lang.Throwable)>(v1);
throw v4;
}
public java.lang.Object get(long, java.util.concurrent.TimeUnit) throws java.lang.InterruptedException, java.util.concurrent.ExecutionException, java.util.concurrent.TimeoutException
{
java.lang.Throwable v4;
io.netty.util.concurrent.AbstractFuture v0;
java.util.concurrent.TimeoutException v8;
long v1;
java.util.concurrent.ExecutionException v7;
java.util.concurrent.TimeUnit v2;
java.lang.Object v5;
boolean v3, v6;
v0 := @this: io.netty.util.concurrent.AbstractFuture;
v1 := @parameter0: long;
v2 := @parameter1: java.util.concurrent.TimeUnit;
v3 = virtualinvoke v0.<io.netty.util.concurrent.AbstractFuture: boolean await(long,java.util.concurrent.TimeUnit)>(v1, v2);
if v3 == 0 goto label3;
v4 = virtualinvoke v0.<io.netty.util.concurrent.AbstractFuture: java.lang.Throwable cause()>();
if v4 != null goto label1;
v5 = virtualinvoke v0.<io.netty.util.concurrent.AbstractFuture: java.lang.Object getNow()>();
return v5;
label1:
v6 = v4 instanceof java.util.concurrent.CancellationException;
if v6 == 0 goto label2;
throw v4;
label2:
v7 = new java.util.concurrent.ExecutionException;
specialinvoke v7.<java.util.concurrent.ExecutionException: void <init>(java.lang.Throwable)>(v4);
throw v7;
label3:
v8 = new java.util.concurrent.TimeoutException;
specialinvoke v8.<java.util.concurrent.TimeoutException: void <init>()>();
throw v8;
}
}