class io.netty.channel.AbstractChannel$AbstractUnsafe$5 extends java.lang.Object implements java.lang.Runnable
{
final io.netty.channel.ChannelPromise val$promise;
final io.netty.channel.ChannelOutboundBuffer val$outboundBuffer;
final java.lang.Throwable val$cause;
final boolean val$notify;
final java.nio.channels.ClosedChannelException val$closeCause;
final boolean val$wasActive;
final io.netty.channel.AbstractChannel$AbstractUnsafe this$1;
void <init>(io.netty.channel.AbstractChannel$AbstractUnsafe, io.netty.channel.ChannelPromise, io.netty.channel.ChannelOutboundBuffer, java.lang.Throwable, boolean, java.nio.channels.ClosedChannelException, boolean)
{
java.lang.Throwable v4;
java.nio.channels.ClosedChannelException v6;
io.netty.channel.AbstractChannel$AbstractUnsafe v1;
io.netty.channel.AbstractChannel$AbstractUnsafe$5 v0;
io.netty.channel.ChannelOutboundBuffer v3;
io.netty.channel.ChannelPromise v2;
boolean v5, v7;
v0 := @this: io.netty.channel.AbstractChannel$AbstractUnsafe$5;
v1 := @parameter0: io.netty.channel.AbstractChannel$AbstractUnsafe;
v2 := @parameter1: io.netty.channel.ChannelPromise;
v3 := @parameter2: io.netty.channel.ChannelOutboundBuffer;
v4 := @parameter3: java.lang.Throwable;
v5 := @parameter4: boolean;
v6 := @parameter5: java.nio.channels.ClosedChannelException;
v7 := @parameter6: boolean;
v0.<io.netty.channel.AbstractChannel$AbstractUnsafe$5: io.netty.channel.AbstractChannel$AbstractUnsafe this$1> = v1;
v0.<io.netty.channel.AbstractChannel$AbstractUnsafe$5: io.netty.channel.ChannelPromise val$promise> = v2;
v0.<io.netty.channel.AbstractChannel$AbstractUnsafe$5: io.netty.channel.ChannelOutboundBuffer val$outboundBuffer> = v3;
v0.<io.netty.channel.AbstractChannel$AbstractUnsafe$5: java.lang.Throwable val$cause> = v4;
v0.<io.netty.channel.AbstractChannel$AbstractUnsafe$5: boolean val$notify> = v5;
v0.<io.netty.channel.AbstractChannel$AbstractUnsafe$5: java.nio.channels.ClosedChannelException val$closeCause> = v6;
v0.<io.netty.channel.AbstractChannel$AbstractUnsafe$5: boolean val$wasActive> = v7;
specialinvoke v0.<java.lang.Object: void <init>()>();
return;
}
public void run()
{
java.lang.Throwable v5;
io.netty.channel.AbstractChannel$AbstractUnsafe v1, v3, v6;
io.netty.channel.AbstractChannel$AbstractUnsafe$5$1 v4, v7;
io.netty.channel.AbstractChannel$AbstractUnsafe$5 v0;
io.netty.channel.ChannelPromise v2;
v0 := @this: io.netty.channel.AbstractChannel$AbstractUnsafe$5;
label1:
v1 = v0.<io.netty.channel.AbstractChannel$AbstractUnsafe$5: io.netty.channel.AbstractChannel$AbstractUnsafe this$1>;
v2 = v0.<io.netty.channel.AbstractChannel$AbstractUnsafe$5: io.netty.channel.ChannelPromise val$promise>;
specialinvoke v1.<io.netty.channel.AbstractChannel$AbstractUnsafe: void doClose0(io.netty.channel.ChannelPromise)>(v2);
label2:
v3 = v0.<io.netty.channel.AbstractChannel$AbstractUnsafe$5: io.netty.channel.AbstractChannel$AbstractUnsafe this$1>;
v4 = new io.netty.channel.AbstractChannel$AbstractUnsafe$5$1;
specialinvoke v4.<io.netty.channel.AbstractChannel$AbstractUnsafe$5$1: void <init>(io.netty.channel.AbstractChannel$AbstractUnsafe$5)>(v0);
specialinvoke v3.<io.netty.channel.AbstractChannel$AbstractUnsafe: void invokeLater(java.lang.Runnable)>(v4);
goto label4;
label3:
v5 := @caughtexception;
v6 = v0.<io.netty.channel.AbstractChannel$AbstractUnsafe$5: io.netty.channel.AbstractChannel$AbstractUnsafe this$1>;
v7 = new io.netty.channel.AbstractChannel$AbstractUnsafe$5$1;
specialinvoke v7.<io.netty.channel.AbstractChannel$AbstractUnsafe$5$1: void <init>(io.netty.channel.AbstractChannel$AbstractUnsafe$5)>(v0);
specialinvoke v6.<io.netty.channel.AbstractChannel$AbstractUnsafe: void invokeLater(java.lang.Runnable)>(v7);
throw v5;
label4:
return;
catch java.lang.Throwable from label1 to label2 with label3;
}
}