public class io.vertx.ext.auth.authentication.CredentialValidationException extends java.lang.RuntimeException
{
public void <init>(java.lang.String)
{
java.lang.String v1;
io.vertx.ext.auth.authentication.CredentialValidationException v0;
v0 := @this: io.vertx.ext.auth.authentication.CredentialValidationException;
v1 := @parameter0: java.lang.String;
specialinvoke v0.<java.lang.RuntimeException: void <init>(java.lang.String)>(v1);
return;
}
public void <init>(java.lang.String, java.lang.Throwable)
{
java.lang.Throwable v2;
java.lang.String v1;
io.vertx.ext.auth.authentication.CredentialValidationException v0;
v0 := @this: io.vertx.ext.auth.authentication.CredentialValidationException;
v1 := @parameter0: java.lang.String;
v2 := @parameter1: java.lang.Throwable;
specialinvoke v0.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>(v1, v2);
return;
}
}