class io.netty.util.internal.ThreadLocalRandom$2 extends java.lang.Object implements java.lang.Thread$UncaughtExceptionHandler
{
void <init>()
{
io.netty.util.internal.ThreadLocalRandom$2 v0;
v0 := @this: io.netty.util.internal.ThreadLocalRandom$2;
specialinvoke v0.<java.lang.Object: void <init>()>();
return;
}
public void uncaughtException(java.lang.Thread, java.lang.Throwable)
{
java.lang.Throwable v2;
io.netty.util.internal.logging.InternalLogger v3;
java.lang.Thread v1;
io.netty.util.internal.ThreadLocalRandom$2 v0;
java.lang.String v4;
v0 := @this: io.netty.util.internal.ThreadLocalRandom$2;
v1 := @parameter0: java.lang.Thread;
v2 := @parameter1: java.lang.Throwable;
v3 = <io.netty.util.internal.ThreadLocalRandom: io.netty.util.internal.logging.InternalLogger logger>;
v4 = virtualinvoke v1.<java.lang.Thread: java.lang.String getName()>();
interfaceinvoke v3.<io.netty.util.internal.logging.InternalLogger: void debug(java.lang.String,java.lang.Object,java.lang.Object)>("An exception has been raised by {}", v4, v2);
return;
}
}