public final class io.vertx.core.net.impl.ConnectionBase$lambda_handleException_4__1372 extends java.lang.Object implements io.vertx.core.Handler
{
io.vertx.core.net.impl.ConnectionBase cap0;
java.lang.Throwable cap1;
public static io.vertx.core.Handler bootstrap$(io.vertx.core.net.impl.ConnectionBase, java.lang.Throwable)
{
java.lang.Throwable v1;
io.vertx.core.net.impl.ConnectionBase$lambda_handleException_4__1372 v2;
io.vertx.core.net.impl.ConnectionBase v0;
v0 := @parameter0: io.vertx.core.net.impl.ConnectionBase;
v1 := @parameter1: java.lang.Throwable;
v2 = new io.vertx.core.net.impl.ConnectionBase$lambda_handleException_4__1372;
specialinvoke v2.<io.vertx.core.net.impl.ConnectionBase$lambda_handleException_4__1372: void <init>(io.vertx.core.net.impl.ConnectionBase,java.lang.Throwable)>(v0, v1);
return v2;
}
public void <init>(io.vertx.core.net.impl.ConnectionBase, java.lang.Throwable)
{
java.lang.Throwable v2;
io.vertx.core.net.impl.ConnectionBase$lambda_handleException_4__1372 v0;
io.vertx.core.net.impl.ConnectionBase v1;
v0 := @this: io.vertx.core.net.impl.ConnectionBase$lambda_handleException_4__1372;
v1 := @parameter0: io.vertx.core.net.impl.ConnectionBase;
v2 := @parameter1: java.lang.Throwable;
specialinvoke v0.<java.lang.Object: void <init>()>();
v0.<io.vertx.core.net.impl.ConnectionBase$lambda_handleException_4__1372: io.vertx.core.net.impl.ConnectionBase cap0> = v1;
v0.<io.vertx.core.net.impl.ConnectionBase$lambda_handleException_4__1372: java.lang.Throwable cap1> = v2;
return;
}
public void handle(java.lang.Object)
{
java.lang.Throwable v3;
io.vertx.core.net.impl.ConnectionBase$lambda_handleException_4__1372 v0;
java.lang.Object v1;
io.vertx.core.net.impl.ConnectionBase v2;
v0 := @this: io.vertx.core.net.impl.ConnectionBase$lambda_handleException_4__1372;
v1 := @parameter0: java.lang.Object;
v2 = v0.<io.vertx.core.net.impl.ConnectionBase$lambda_handleException_4__1372: io.vertx.core.net.impl.ConnectionBase cap0>;
v3 = v0.<io.vertx.core.net.impl.ConnectionBase$lambda_handleException_4__1372: java.lang.Throwable cap1>;
specialinvoke v2.<io.vertx.core.net.impl.ConnectionBase: void lambda$handleException$4(java.lang.Throwable,java.lang.Throwable)>(v3, v1);
return;
}
}