class org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector extends java.lang.Object implements java.lang.Runnable
{
private int attempts;
final org.jboss.logmanager.handlers.TcpOutputStream this$0;
private void <init>(org.jboss.logmanager.handlers.TcpOutputStream)
{
org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector v0;
org.jboss.logmanager.handlers.TcpOutputStream v1;
v0 := @this: org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector;
v1 := @parameter0: org.jboss.logmanager.handlers.TcpOutputStream;
v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: org.jboss.logmanager.handlers.TcpOutputStream this$0> = v1;
specialinvoke v0.<java.lang.Object: void <init>()>();
v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: int attempts> = 0;
return;
}
public void run()
{
java.lang.Throwable v14, v28, v29;
java.net.Socket v4;
long v23;
org.jboss.logmanager.handlers.TcpOutputStream v11, v12, v13, v16, v2, v25, v27, v5, v7;
byte v19;
java.lang.Thread v9;
int v17, v18, v20, v21;
boolean v1, v10;
org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector v0;
java.io.IOException v15;
java.util.concurrent.TimeUnit v22;
org.jboss.logmanager.handlers.ClientSocketFactory v3, v6;
java.lang.InterruptedException v24;
java.lang.Object v26, v8;
v0 := @this: org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector;
v1 = 0;
label01:
v2 = v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: org.jboss.logmanager.handlers.TcpOutputStream this$0>;
v3 = v2.<org.jboss.logmanager.handlers.TcpOutputStream: org.jboss.logmanager.handlers.ClientSocketFactory socketFactory>;
if v3 == null goto label20;
if v1 != 0 goto label20;
v4 = null;
label02:
v5 = v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: org.jboss.logmanager.handlers.TcpOutputStream this$0>;
v6 = v5.<org.jboss.logmanager.handlers.TcpOutputStream: org.jboss.logmanager.handlers.ClientSocketFactory socketFactory>;
v4 = interfaceinvoke v6.<org.jboss.logmanager.handlers.ClientSocketFactory: java.net.Socket createSocket()>();
v7 = v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: org.jboss.logmanager.handlers.TcpOutputStream this$0>;
v8 = v7.<org.jboss.logmanager.handlers.TcpOutputStream: java.lang.Object outputLock>;
entermonitor v8;
label03:
v9 = staticinvoke <java.lang.Thread: java.lang.Thread currentThread()>();
v10 = virtualinvoke v9.<java.lang.Thread: boolean isInterrupted()>();
if v10 == 0 goto label05;
staticinvoke <org.jboss.logmanager.handlers.TcpOutputStream: void safeClose(java.io.Closeable)>(v4);
exitmonitor v8;
label04:
if v1 != 0 goto label20;
staticinvoke <org.jboss.logmanager.handlers.TcpOutputStream: void safeClose(java.io.Closeable)>(v4);
goto label20;
label05:
v11 = v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: org.jboss.logmanager.handlers.TcpOutputStream this$0>;
v11.<org.jboss.logmanager.handlers.TcpOutputStream: java.net.Socket socket> = v4;
v12 = v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: org.jboss.logmanager.handlers.TcpOutputStream this$0>;
v12.<org.jboss.logmanager.handlers.TcpOutputStream: boolean connected> = 1;
v13 = v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: org.jboss.logmanager.handlers.TcpOutputStream this$0>;
v13.<org.jboss.logmanager.handlers.TcpOutputStream: java.lang.Thread reconnectThread> = null;
v1 = 1;
exitmonitor v8;
label06:
goto label01;
label07:
v14 := @caughtexception;
exitmonitor v8;
throw v14;
label08:
v15 := @caughtexception;
v1 = 0;
v16 = v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: org.jboss.logmanager.handlers.TcpOutputStream this$0>;
specialinvoke v16.<org.jboss.logmanager.handlers.TcpOutputStream: void addError(java.lang.Exception)>(v15);
v17 = v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: int attempts>;
v18 = v17 + 1;
v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: int attempts> = v18;
v19 = v17 cmp 0L;
if v19 <= 0 goto label09;
v20 = v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: int attempts>;
v21 = 10 * v20;
goto label10;
label09:
v21 = 5L;
label10:
v22 = <java.util.concurrent.TimeUnit: java.util.concurrent.TimeUnit SECONDS>;
v23 = staticinvoke <java.lang.Math: long min(long,long)>(v21, 40L);
virtualinvoke v22.<java.util.concurrent.TimeUnit: void sleep(long)>(v23);
label11:
goto label17;
label12:
v24 := @caughtexception;
v25 = v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: org.jboss.logmanager.handlers.TcpOutputStream this$0>;
v26 = v25.<org.jboss.logmanager.handlers.TcpOutputStream: java.lang.Object outputLock>;
entermonitor v26;
label13:
v27 = v0.<org.jboss.logmanager.handlers.TcpOutputStream$RetryConnector: org.jboss.logmanager.handlers.TcpOutputStream this$0>;
v27.<org.jboss.logmanager.handlers.TcpOutputStream: boolean connected> = 0;
exitmonitor v26;
label14:
goto label16;
label15:
v28 := @caughtexception;
exitmonitor v26;
throw v28;
label16:
staticinvoke <org.jboss.logmanager.handlers.TcpOutputStream: void safeClose(java.io.Closeable)>(v4);
goto label20;
label17:
staticinvoke <org.jboss.logmanager.handlers.TcpOutputStream: void safeClose(java.io.Closeable)>(v4);
goto label01;
label18:
v29 := @caughtexception;
if v1 != 0 goto label19;
staticinvoke <org.jboss.logmanager.handlers.TcpOutputStream: void safeClose(java.io.Closeable)>(v4);
label19:
throw v29;
label20:
return;
catch java.lang.Throwable from label03 to label04 with label07;
catch java.lang.Throwable from label05 to label06 with label07;
catch java.io.IOException from label02 to label04 with label08;
catch java.io.IOException from label05 to label08 with label08;
catch java.lang.InterruptedException from label10 to label11 with label12;
catch java.lang.Throwable from label13 to label14 with label15;
catch java.lang.Throwable from label02 to label04 with label18;
catch java.lang.Throwable from label05 to label08 with label18;
catch java.lang.Throwable from label08 to label16 with label18;
}
}